### ISSUE TITLE
Settings page crashes

### ISSUE THREAD

**Issue by wesharper** [theTaoTeam/snuze_app#12]
I tried running the app using the simulator after pulling the most recent changes.

Upon startup, the app was already at the alarm page. I'm unsure if I was properly authenticated or not. When I clicked the settings icon I received a "Failed assertion: boolean expression must not be null" error.

**Comment by sclampet** [comment]
I think this is because when you had logged in before, a darkTheme key wasn't added to local storage but a token and email were, so now with autoAuthenticate on you are still logged in but the settings page is returning a null value. This should be a unique case where this happens.

Try commenting out autoAuthenticate in the main.dart and log back in. It should be fine

**Comment by sclampet** [comment]
Is this still crashing? If not go ahead and close this

**Comment by wesharper** [comment]
I think you're right.
